[package]
name = "base2"
version = "0.3.1"
authors = ["Sergey Shandar"]
description = "Base-2 functions"
license = "Apache-2.0"
repository = "https://github.com/rust-common/base2"

[dependencies]
int = "0.3.0"
